version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      web-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
    groups:
      container-images:
        patterns: ["*"]
